services:
  eurofmx_manager:
    image: ghcr.io/emiliocimino/project_assistant:0.1.0-dev-9c1fb20
    container_name: project_assistant
    environment:
      - API_KEY=${API_KEY}
      - API_URL=https://ollama.com/v1
      - MODEL_NAME="gemma4:31b-cloud"
      - LANGSMITH_TRACING=false
      - LANGSMITH_ENDPOINT=https://api.smith.langchain.com
      - LANGSMITH_API_KEY=&{LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT="Project Assistant"
    ports:
      - "7860:7860"
    volumes:
      - ./data:/home/src/data